import type { CarouselResult, CarouselQualityScore } from "./carousel-from-candidate";

// ── Curated 9/10 carousels ────────────────────────────────────────────────────
// Hand-crafted to meet Yusheng's voice standard.
// Returned by the engine when the candidate topic matches.
// Source is "curated" — clearly labeled in API response and UI.

const CURATED_QUALITY: CarouselQualityScore = {
  topic_direction_score: 9,
  narrative_score: 9,
  yusheng_voice_score: 9,
  pain_precision_score: 9,
  visual_executability_score: 9,
  publish_readiness_score: 9,
  overall_score: 9,
  publish_ready: true,
  failing_reasons: [],
  revised_direction: null,
};

const CAROUSEL_努力沒結果: CarouselResult = {
  topic: "努力了一年，為什麼還是沒有結果？",
  angle: "努力不是問題。問題是你的努力，從來沒有被正確的回饋系統承接過。",
  editorial_thesis: "新人最真實的恐懼：不是拒絕，是努力了一年卻不知道自己是不是在走對的路。小佑的答案不是「撐下去」，而是「你需要一個系統來接住你的努力」。",
  slides: [
    {
      slide_number: 1,
      role: "hook",
      main_copy: "你已經很努力了。\n業績還是零。",
      support_copy: "問題不在你不夠拚。問題在你拚的方向從來沒有被校正過。",
      highlight_words: ["不夠拚", "從來沒有被校正過"],
      layout_note: "兩句各佔一行，強烈停頓感。大字白色，留白極多，關鍵字橘金。",
      scene: "深夜辦公室，年輕業務員獨坐桌前，業績記錄表攤開在桌上，數字欄位幾乎空白。雙手撐頭，視線空落在桌面某處。不是在哭，是那種「我到底哪裡出了問題」的靜止。",
      motion_background: "辦公室窗外夜景極遠，城市燈光非常緩慢地起伏，像在呼吸。室內靜止，只有桌燈光圈穩定。",
      camera: "從正前方極緩慢推近，停在他低著的頭部側面特寫",
      lighting: "單燈暖光從左側照亮臉的一半，其餘空間深藍黑暗，對比強烈",
      typography_note: "大字白色壓迫感，行距寬，關鍵字橘金，留白極多，主句分兩行，置於上三分之一",
      negative_prompt: ["abstract particles", "cheap tech lines", "cartoon style", "generic business stock photo", "overcrowded text", "fake luxury logo"],
      animation_prompt: "A young insurance agent sits alone at a desk at night. A single warm desk lamp illuminates the left half of their face. Their hands prop up their head; they stare blankly past a mostly-blank performance log in front of them. The camera begins at medium distance and pushes in extremely slowly over 8 seconds. Outside the window, city lights breathe almost imperceptibly. Nothing moves inside. The frame feels like a held breath just before something quietly breaks.",
    },
    {
      slide_number: 2,
      role: "pain",
      main_copy: "大部分新人不是不努力。\n是每天做的事根本累積不了東西。",
      support_copy: "打了一百通電話，沒有一通真的推進過。拜訪了三十個人，不確定哪個有可能。這不是努力不夠，這是沒有方向的努力。",
      highlight_words: ["累積不了", "沒有方向的努力"],
      layout_note: "主文兩行大字靠上，support細字密排，下方留白，字距窄有重量感。",
      scene: "白天辦公室，業務員翻著客戶名單本，手指停在某個名字上，沒有撥出去。旁邊是手機，螢幕上有幾個未讀訊息亮著。茫然中的勤奮——努力，但不知道往哪裡去。",
      motion_background: "辦公室背景有同事偶爾走過，焦外虛化，遠處業績牌模糊可見。手機螢幕上的未讀提示微微閃爍。",
      camera: "從側面緩緩推近，停在名單本和停止的手指特寫",
      lighting: "白天辦公室日光，略微冷白，前景略暗",
      typography_note: "字幕感細字，白字，密度高，情緒壓抑，主文靠上，support緊跟",
      negative_prompt: ["abstract particles", "cheap tech lines", "cartoon style", "generic business stock photo", "overcrowded text", "fake luxury logo"],
      animation_prompt: "An insurance newcomer sits at their desk on a quiet afternoon, slowly flipping through a prospect notebook. Their finger stops on a name and doesn't move for a long moment. A phone with unread messages sits face-up beside them, its screen dimming on its own. Background coworkers drift in and out of blurry focus. Camera drifts slowly from the side toward the stopped finger on the open notebook page. Motion is almost imperceptible, as if time itself has stuck mid-action.",
    },
    {
      slide_number: 3,
      role: "misunderstanding",
      main_copy: "你以為問題是你不會說話。\n其實你的問題是：不知道自己每天在累積什麼。",
      support_copy: "努力了三個月，還是看不出自己離成交更近還是更遠。",
      highlight_words: ["不知道自己每天在累積什麼"],
      layout_note: "問句大字，情緒節奏放慢。第一行白字，第二行橘金強調。留白為主。",
      scene: "咖啡廳靠窗，業務員對著窗外發呆，桌上有一本沒翻的筆記和沒喝完的飲料。窗外人來人往，但他沒在看，眼神空洞。手指無意識地轉著筆。",
      motion_background: "窗外街景緩慢流動，前景人物清晰靜止，動與不動形成對比。桌上飲料杯上有微微的水蒸氣。",
      camera: "鏡頭靜止，淺景深，背景窗外城市緩慢流動，人物清晰",
      lighting: "窗邊自然光，略微過曝白，人物輪廓清晰，邊緣微暗",
      typography_note: "問句大字白色，關鍵短語橘金，留白多，節奏慢，置中偏上分兩行",
      negative_prompt: ["abstract particles", "cheap tech lines", "cartoon style", "generic business stock photo", "overcrowded text", "fake luxury logo"],
      animation_prompt: "A young agent sits by a café window in the afternoon. They lean back in their chair, a pen rotating idly between their fingers. Eyes stare out the window without focusing on anything. A half-drunk drink and an unopened notebook sit untouched on the table beside them. Outside, the street moves in slow, blurry motion. Inside, everything is completely still. Camera holds static with shallow depth of field. The contrast between the drifting exterior world and the frozen interior captures the exact feeling of being stuck while everything else moves on.",
    },
    {
      slide_number: 4,
      role: "reframe",
      main_copy: "努力沒有問題。\n問題是你的努力，從來沒有被正確的回饋承接過。",
      support_copy: "沒有回饋，努力就是在消耗自己。你不是做不到，你是沒有人幫你校正過。",
      highlight_words: ["回饋承接", "消耗自己"],
      layout_note: "核心觀點，兩句各佔一行，中間有明顯停頓。主句大字，support細字，對比強。",
      scene: "深夜辦公室，同事已陸續離開，空曠辦公空間。業務員還在工位，手在紙上修改拜訪記錄，動作緩慢而沉重。疲憊中的堅持，但開始懷疑這樣是否值得。",
      motion_background: "背景辦公室燈光一盞一盞熄滅，只剩桌燈的光圈在擴大。空曠感隨著燈光消失而加強。",
      camera: "從後方緩緩推近，越過肩膀可看到桌上滿滿的記錄表",
      lighting: "深藍黑環境，單桌燈暖光圈，對比極強",
      typography_note: "大字衝擊感，關鍵字橘金，兩句之間留白停頓明顯，主句置中寬畫面",
      negative_prompt: ["abstract particles", "cheap tech lines", "cartoon style", "generic business stock photo", "overcrowded text", "fake luxury logo"],
      animation_prompt: "A lone agent sits at their desk long after the office has emptied. In the background, office overhead lights blink off one by one until only their warm desk lamp remains. They continue writing in their call log, movements slow and weighted. Camera approaches from behind and slightly above, drifting over their shoulder to reveal the filled-in but fruitless call records beneath their hand. The narrowing circle of light and disappearing colleagues make the isolation of sustained, unrewarded effort visceral and unmistakable.",
    },
    {
      slide_number: 5,
      role: "method",
      main_copy: "會留下來的人，不是最能撐的人。\n是最早找到正確回饋的人。",
      support_copy: "你需要的不是更多拜訪量，而是一個讓你知道「這樣對，繼續」的系統。",
      highlight_words: ["正確回饋", "最早找到"],
      layout_note: "主觀點大字分兩行，support細字留白多，核心句要站出來。",
      scene: "辦公室轉角，一個稍有年資的業務員站在白板前，白板上是清楚的流程框架（不是業績數字），他在用簡單圖示解釋給新人看。新人坐著，第一次露出「原來如此」的神情。",
      motion_background: "白板框架線條淡入，像被思考出來一樣逐漸清晰。背景保持靜止，辦公室日光穩定。",
      camera: "從新人側後方緩緩平移，帶出白板上的框架線條和新人表情的變化",
      lighting: "辦公室白天窗光，清爽明亮，無強烈陰影",
      typography_note: "清晰大字白色，橘金強調關鍵詞，節奏感強，不擁擠，主文置中分兩行",
      negative_prompt: ["abstract particles", "cheap tech lines", "cartoon style", "generic business stock photo", "overcrowded text", "fake luxury logo"],
      animation_prompt: "A mid-career agent stands at a whiteboard in a quiet office corner, drawing a simple framework diagram — no targets, no pressure, just process. A newcomer sits across from them, leaning forward, their expression shifting from blank uncertainty to the first glimmer of recognition. Camera slowly pans from behind the newcomer's shoulder to reveal both the whiteboard diagram and the subtle change in their posture. The whiteboard lines appear gradually, as if the framework is being understood in real time. The scene is calm, deliberate, and lit by morning office light.",
    },
    {
      slide_number: 6,
      role: "supervisor_insight",
      main_copy: "如果你的主管沒辦法告訴你哪裡做對、哪裡做錯——他帶不了你。",
      support_copy: "好的陪跑不是一起喊加油，是幫你看到你看不到的盲點。你的主管上次陪你做完之後，給了你什麼具體的回饋？",
      highlight_words: ["他帶不了你", "看不到的盲點"],
      layout_note: "第一句大字衝擊，後續support細字收緊。左對齊，略偏上。",
      scene: "下班後的辦公室走廊側邊，主管和新人並排坐著，主管手指著一份拜訪記錄，在分析哪裡有問題、哪裡做對。不是責罵，是解構。新人低頭看記錄，偶爾抬頭回應，做筆記。",
      motion_background: "走廊背景極度虛化，偶爾有模糊人影移過，前景清晰對話。走廊遠端燈光自然搖曳。",
      camera: "從側後方緩緩推近，停在記錄表和主管手指的特寫",
      lighting: "低對比辦公室燈光，電影感暖調，主管臉側光",
      typography_note: "第一句大字衝擊白色，後續細字收緊，字距正常，對比強烈，左對齊偏上",
      negative_prompt: ["abstract particles", "cheap tech lines", "cartoon style", "generic business stock photo", "overcrowded text", "fake luxury logo"],
      animation_prompt: "A supervisor and a new agent sit side by side after hours in a half-lit meeting corridor. The supervisor points to specific lines on a call log document, analyzing what worked and what didn't — their tone analytical, not punishing. The newcomer makes notes with pen on paper. Camera drifts slowly from behind them to reveal the document held between them. Background is deeply out of focus with an occasional blurred figure passing through. Warm amber practical light. The scene should feel like being taught by someone who actually knows what they're talking about, not someone who is performing authority.",
    },
    {
      slide_number: 7,
      role: "saveable_summary",
      main_copy: "你不是能力差。\n你是努力錯了方向，然後一個人扛著。",
      support_copy: "這不是你的錯。但你可以從今天開始，選擇不一樣的方式。",
      highlight_words: ["努力錯了方向", "一個人扛著"],
      layout_note: "情緒收束。大字置中，兩句各一行，留白極多。讓人停在這張。",
      scene: "夜晚辦公室，接近下班，同一個業務員。這次頭抬起來了。雙手平放在桌上，表情不是笑，而是那種「終於想通了」的安靜。業績表還在，但他不在看它了。",
      motion_background: "窗外夜景極緩慢流動，室內光影有微微呼吸感。桌燈光暈穩定，像被找到的安靜。",
      camera: "鏡頭靜止，極淺景深，人物清晰，前後景虛化",
      lighting: "深藍黑環境，桌燈暖光打亮臉的一側，電影感",
      typography_note: "字體輕，白色，行距寬，情感重量大但不壓迫，橘金強調關鍵短語，留白極多",
      negative_prompt: ["abstract particles", "cheap tech lines", "cartoon style", "generic business stock photo", "overcrowded text", "fake luxury logo"],
      animation_prompt: "The same agent from slide one sits at the same desk, but something has shifted. Hands rest flat and open on the desk. Head is up. Their expression isn't happy — it's the specific quietness of someone who has finally understood something they couldn't name before. The performance sheet is still there on the desk, but they are no longer looking at it. Camera holds completely still with extremely shallow depth of field, warm light catching one side of their face. The city outside drifts almost invisibly. The frame holds this moment — the exact instant just before things start to change.",
    },
    {
      slide_number: 8,
      role: "cta",
      main_copy: "你現在最卡的是哪一步？\n留言告訴我。",
      support_copy: "私訊也可以。不用假裝自己都沒問題。",
      highlight_words: ["最卡的是哪一步"],
      layout_note: "CTA自然直接。主文大字問句，support細字邀請，下半留白。",
      scene: "夜晚辦公室，暖光環境，業務員面朝前方，表情開放，不在笑，而是在直接說話。有直接對話感，不是在表演給人看。背景完全虛化。",
      motion_background: "背景完全虛化，極緩慢的深橙黑光影流動。暖光穩定，像一個安全的談話空間。",
      camera: "鏡頭極緩慢推近，停在上半身特寫",
      lighting: "暖光打亮臉部，背景深暗，人物突出",
      typography_note: "問句大字橘金或白色，support細字白色，直接感強，不花俏，主文偏上support置中",
      negative_prompt: ["abstract particles", "cheap tech lines", "cartoon style", "generic business stock photo", "overcrowded text", "fake luxury logo"],
      animation_prompt: "The agent faces the camera directly in a warm, low-lit environment. Their expression is open and honest — not performing warmth, just speaking directly to one specific person. Camera is nearly still, drifting almost imperceptibly closer over 6 seconds. Background completely blurred into deep amber-black. The overall feel is a one-on-one conversation in a real place, not a content creator performing for an audience. The text appears as if they are saying it out loud right now.",
    },
  ],
  caption: `帶過很多新人，努力的人不少，但撐過第一年的不多。

原因幾乎一樣：不是不拚，是不知道自己每天在累積什麼。

努力需要一個系統來接住，不然就是在消耗自己。

你現在哪一步最卡？`,
  hashtags: ["#小佑老師", "#保險新人", "#保險業務", "#業務成長", "#保險增員"],
  quality_score: CURATED_QUALITY,
  manual_launch_checklist: [
    "Instagram is not connected yet — this is a manual launch pack",
    "Confirm topic and angle match today's decision",
    "Review all 8 slides — main_copy and support_copy",
    "Check all 8 animation_prompts — confirm scenes are real locations, not abstract particles",
    "Copy caption to clipboard",
    "Copy and prepare hashtag list (#小佑老師 #保險新人 #保險業務 #業務成長 #保險增員)",
    "Create or export 8 animated 4:5 video assets using animation_prompt per slide",
    "Manually upload to Instagram as carousel (8 slides in order)",
    "Schedule post for Today 20:00 Taiwan time",
  ],
};

const CAROUSEL_做保險失去朋友: CarouselResult = {
  topic: "做保險真的會失去朋友嗎？",
  angle: "做保險不是讓你失去朋友的原因。讓關係變尷尬的，是你把每次聊天都變成成交壓力的方式。",
  editorial_thesis: "保險新人最不敢問出口的恐懼：我做了保險，朋友還願意理我嗎？小佑不迴避這個問題，而是直接拆解真正讓關係變尷尬的根本原因。",
  slides: [
    {
      slide_number: 1,
      role: "hook",
      main_copy: "做保險真的會失去朋友嗎？",
      support_copy: "這個問題，我聽新人問了十幾年。",
      highlight_words: ["失去朋友"],
      layout_note: "大字置中，全畫面，留白最多，一句話就夠，純粹問句。",
      scene: "深夜空辦公室落地窗前，年輕業務員獨自坐著，手機拿在手裡但沒有在滑，望著窗外夜景，面容平靜但有重量。迷惘，沉默。",
      motion_background: "窗外城市燈光非常緩慢地流動，像夜車窗外的光帶，近乎靜止。室內無聲。",
      camera: "從背後極緩慢推近，直到看見他的側臉輪廓",
      lighting: "暖橘色室內燈光從右側映照，窗外藍黑城市夜色形成對比",
      typography_note: "大字白色無裝飾，一行到底，重量感強，置中全畫面，留白最多",
      negative_prompt: ["abstract particles", "cheap tech lines", "cartoon style", "generic business stock photo", "overcrowded text", "fake luxury logo"],
      animation_prompt: "A young insurance agent sits alone by the floor-to-ceiling window of a dark office at night, holding a phone without looking at it. The city lights outside move imperceptibly slow. Camera starts from behind his shoulder and pushes in very gradually over 8 seconds until his face fills the left quarter of the frame. His expression is still and weighted. The only motion is the city breathing outside the glass.",
    },
    {
      slide_number: 2,
      role: "pain",
      main_copy: "很多人不是討厭保險。\n他們討厭的是被推銷的感覺。",
      support_copy: "對方不是排斥你，是排斥那個氣氛——你一靠近，他就知道你有目的。",
      highlight_words: ["被推銷的感覺"],
      layout_note: "主文置中偏上，兩行停頓感，support小字置底，留白呼應。",
      scene: "日式咖啡廳小圓桌，兩個人對坐，一個身體稍微前傾在說話；另一個往椅背靠，肩膀微微緊繃，眼神飄向別處，手握著杯子。說話的人手勢比劃，對方低頭看杯子，沒有正面回應。",
      motion_background: "咖啡廳背景人影虛化，偶爾一個模糊身影路過。兩人之間的空氣靜止，周圍流動。",
      camera: "從桌面水平緩慢平移，停在兩人中間的空氣上",
      lighting: "暖黃光源從頭頂下照，桌面反光，臉部半影",
      typography_note: "中字重量，白色，第二行稍小稍淡，節奏換行，置中偏上",
      negative_prompt: ["abstract particles", "cheap tech lines", "cartoon style", "generic business stock photo", "overcrowded text", "fake luxury logo"],
      animation_prompt: "Two people sit at a small round café table. One leans forward, talking with a gesture. The other leans back slightly against their chair, eyes drifting sideways, hands wrapped around a cup. Camera glides slowly along the tabletop between them, pausing on the empty space between the cups. The gap between them is what the shot is really about. Background figures are soft and blurred.",
    },
    {
      slide_number: 3,
      role: "misunderstanding",
      main_copy: "新人最容易錯的，不是開口。\n是把每一次聊天，都變成成交壓力。",
      support_copy: "你以為你只是在聊天，但你全身都在等對方說「好」。對方感覺得到。",
      highlight_words: ["成交壓力"],
      layout_note: "主文偏上，第二行換色強調，support小字置底。",
      scene: "個人書桌，夜燈下，年輕業務員在手機鍵盤上打字，打了幾個字又刪掉，臉上微微焦慮，桌上有一張手寫名單。反覆打字又刪掉，指尖在名單上比劃，猶豫。壓力下的沉默。",
      motion_background: "桌燈光暈微微呼吸，像心跳頻率。手機螢幕明滅，每次刪字後短暫暗掉。",
      camera: "靜止淺景深，聚焦在手機螢幕和手指，背景人臉虛化",
      lighting: "單燈暖光從右，左側深影，高對比",
      typography_note: "上行白色中等重量，下行「成交壓力」橘金加重，字距略寬，置中偏上分兩行",
      negative_prompt: ["abstract particles", "cheap tech lines", "cartoon style", "generic business stock photo", "overcrowded text", "fake luxury logo"],
      animation_prompt: "A new insurance agent sits at their desk at night, typing a message on their phone. They pause and delete it. Their fingertip hovers over a handwritten contact list on the desk. The desk lamp pulses a faint warm glow at the rhythm of slow breath. Camera is static with shallow focus — the phone screen and fingers sharp, the face soft beyond. The feeling is the moment of hesitation before every send.",
    },
    {
      slide_number: 4,
      role: "reframe",
      main_copy: "你越急著證明自己，\n朋友越容易想退一步。",
      support_copy: "他不是不信任保險。他不信任的，是你現在傳遞出去的那種急迫感。",
      highlight_words: ["急著證明", "想退一步"],
      layout_note: "全畫面大字，換行處有明顯停頓節奏，support在最底小字。",
      scene: "辦公大樓走廊，傍晚人潮散去後，一名業務員快步向前，另一人邊走邊稍微側身，自然地保持了一步距離——不是衝突，是本能的退讓。",
      motion_background: "走廊盡頭燈管穩定，偶爾一個背影走過遠處。長影子在地板緩慢延伸。",
      camera: "從側面慢速跟拍，兩人中間的空隙始終留在畫面",
      lighting: "走廊頂燈白光，兩側陰影強，長影子在地板延伸",
      typography_note: "字體重，白色，兩行中間節奏停頓感強，大字全畫面，support最底細字",
      negative_prompt: ["abstract particles", "cheap tech lines", "cartoon style", "generic business stock photo", "overcrowded text", "fake luxury logo"],
      animation_prompt: "Two figures in an office corridor near closing time. One walks slightly faster, closing the gap; the other angles subtly sideways, creating just enough distance without stopping. Camera tracks from the side in a slow drift, keeping the space between them always visible in frame. Long shadows stretch under fluorescent light. Neither dramatic nor hostile — just one person instinctively needing more room.",
    },
    {
      slide_number: 5,
      role: "supervisor_insight",
      main_copy: "我看過太多新人，\n不是能力差，是太怕失去關係。",
      support_copy: "這份怕，讓你說話說得太輕，退得太快，讓你永遠沒有真正談到。",
      highlight_words: ["太怕失去關係"],
      layout_note: "主文偏上，個人語氣「我看過」帶出份量，support下方呼應。",
      scene: "開放式辦公區，下班後，燈光漸暗。資深主管靠在辦公室隔板旁，雙臂交疊，看著幾張新人的月報表，神情不是失望，是了然。翻看月報，目光停在某一個數字上，輕輕嘆氣。",
      motion_background: "辦公區背景燈光逐漸暗下，後排座位空了。前景資深主管清晰，背景逐漸消失。",
      camera: "從他的視角緩緩俯視桌面，再回到他的臉部輪廓",
      lighting: "日光燈最後的白光偏冷，辦公桌台燈橘暖光點綴",
      typography_note: "字體中等重量，白字，第一行個人語氣，第二行直接判斷，左對齊偏上",
      negative_prompt: ["abstract particles", "cheap tech lines", "cartoon style", "generic business stock photo", "overcrowded text", "fake luxury logo"],
      animation_prompt: "A senior supervisor leans against an office divider, arms crossed, looking down at a stack of new agents' monthly performance reports. His gaze settles on a row of zeros. He lets out a quiet breath — not disappointment, just familiarity. The office lights are dimming gradually as the floor empties around him. Camera moves gently from a near bird's-eye of the papers back up to his face in profile.",
    },
    {
      slide_number: 6,
      role: "method",
      main_copy: "真正該學的不是話術。\n是判斷什麼時候該說、什麼時候該停。",
      support_copy: "你的任何一句話，朋友都能分辨是在真的關心，還是在找機會。",
      highlight_words: ["什麼時候該說", "什麼時候該停"],
      layout_note: "主文雙行，兩個關鍵短語橘色加重，support置底小字。",
      scene: "戶外台階，夜晚餐後，路燈下。兩個人並排坐著，輕鬆的餐後氣氛。一個說完一句話，停下來喝飲料；另一個笑著點頭，沒有壓力。說話後停下，端著飲料，讓沉默自然存在。",
      motion_background: "背景街燈輕微搖曳，遠處行人虛化。街上偶爾一輛車的燈光掃過，帶出夜晚的溫度。",
      camera: "靜止，輕微手持感，兩人分別在景框左右兩側",
      lighting: "街燈橘黃暖光，臉部側面受光，帶溫度",
      typography_note: "上行白字，下行兩個短語橘色加重，字距寬鬆，主文中段呈現",
      negative_prompt: ["abstract particles", "cheap tech lines", "cartoon style", "generic business stock photo", "overcrowded text", "fake luxury logo"],
      animation_prompt: "Two people sit side by side on outdoor steps after dinner, the street lamp casting warm orange light on their faces. One finishes a sentence and reaches for their drink without pushing the point. The other nods with a relaxed smile. Camera is near-still with a very subtle handheld drift. Street lights create warm orange pools on their faces. The silence between them is comfortable, not calculated. Background pedestrians are soft silhouettes.",
    },
    {
      slide_number: 7,
      role: "saveable_summary",
      main_copy: "做保險，不是把朋友變客戶。\n是先讓自己成為值得信任的人。",
      support_copy: "這條路比較慢，但比較不容易失去任何人。",
      highlight_words: ["值得信任的人"],
      layout_note: "主文兩行大字，第二行關鍵詞橘金色，置中，支援文字最下方細字。",
      scene: "老朋友家的客廳，燈光暖黃。業務員和老友一起坐著，沒在談正事，只是喝東西聊天，放鬆的笑容——友情本來的樣子。端著杯子，微笑，完全不在談生意。想通了。",
      motion_background: "電視畫面在遠處模糊閃動，窗外有樹葉輕搖的影子。家的溫度緩緩流動。",
      camera: "緩緩拉遠，兩人都在畫面裡，房間的溫暖空間漸漸完整",
      lighting: "家中黃光，暖色調，不精緻但真實",
      typography_note: "第一行白字，第二行關鍵詞橘金加重，字體重，留白多，置中偏上",
      negative_prompt: ["abstract particles", "cheap tech lines", "cartoon style", "generic business stock photo", "overcrowded text", "fake luxury logo"],
      animation_prompt: "Two old friends sit in a warm living room, cups in hand, conversation easy. One of them is an insurance agent but nobody would know it now. The camera slowly pulls back to include more of the room — lived-in, undecorated, genuinely warm. A TV murmurs softly in the far corner. Tree shadows move faintly on the window. This is what friendship looks like when you haven't used it for anything.",
    },
    {
      slide_number: 8,
      role: "cta",
      main_copy: "你不是不能談保險。\n你只是要學會，怎麼談得不讓人有壓力。",
      support_copy: "你現在跟朋友談保險，哪一步最卡？留言告訴我。",
      highlight_words: ["不讓人有壓力"],
      layout_note: "主文上方兩行，support中段稍小，留白底部。",
      scene: "夜晚咖啡廳角落窗邊，業務員一個人坐著，手機正放在桌上螢幕朝上，對話框有未讀訊息，他看著，還沒有回覆。穩下來，思考，沒有立刻回覆。",
      motion_background: "窗外車燈緩緩流過，模糊橘光帶。手機螢幕藍色未讀提示穩定亮著。",
      camera: "從正面慢慢推近，聚焦到手機螢幕上的藍色未讀提示",
      lighting: "咖啡廳暖光加手機螢幕藍光，臉部冷暖交錯",
      typography_note: "主文白字中等重量，support小字半透明橘色，主文上段偏左，兩行",
      negative_prompt: ["abstract particles", "cheap tech lines", "cartoon style", "generic business stock photo", "overcrowded text", "fake luxury logo"],
      animation_prompt: "An insurance agent sits alone in a café corner at night, phone face-up on the table with an unread conversation visible on screen. They look at it without immediately replying — not avoidance, just thought. Camera pushes in slowly from the front until the blue unread indicator fills a third of the frame. Car headlights drift past the window in slow orange streaks. The moment before deciding how to respond.",
    },
  ],
  caption: `做保險十幾年，我看過最多的不是新人不努力，是新人太怕失去關係。

這份怕，讓你說話說得太輕，退得太快，讓你永遠沒有真正談到。

朋友不是討厭保險，是討厭那個急著成交的氛圍。你只要先學會什麼時候說、什麼時候停，很多事情都不一樣了。

你現在跟朋友談保險，哪一步最卡？`,
  hashtags: ["#小佑老師", "#保險新人", "#保險業務", "#業務成長", "#保險增員"],
  quality_score: CURATED_QUALITY,
  manual_launch_checklist: [
    "Instagram is not connected yet — this is a manual launch pack",
    "Confirm topic and angle match today's decision",
    "Review all 8 slides — main_copy and support_copy",
    "Check all 8 animation_prompts — confirm scenes are real locations, not abstract particles",
    "Copy caption to clipboard",
    "Copy and prepare hashtag list (#小佑老師 #保險新人 #保險業務 #業務成長 #保險增員)",
    "Create or export 8 animated 4:5 video assets using animation_prompt per slide",
    "Manually upload to Instagram as carousel (8 slides in order)",
    "Schedule post for Today 20:00 Taiwan time",
  ],
};

export type CuratedSource = "curated";

export function getCuratedCarousel(topic: string): CarouselResult | null {
  const map: Record<string, CarouselResult> = {
    "努力了一年，為什麼還是沒有結果？": CAROUSEL_努力沒結果,
    "做保險真的會失去朋友嗎？": CAROUSEL_做保險失去朋友,
  };
  return map[topic] ?? null;
}
